from pydantic import BaseModel, Field

class CopilotQuery(BaseModel):
    query: str = Field(..., min_length=1, description="Natural language question from manager")

class CopilotResponse(BaseModel):
    answer: str = Field(..., description="Natural language response generated by Manager Copilot")
